var campaign_templates=null;let global_recipe_id=""
let hover_over="#e3e3e3"
var selected_template="";const currentDate=new Date();const dateThirtyDaysAgo=new Date(currentDate);dateThirtyDaysAgo.setDate(currentDate.getDate()-30);const epochTimeThirtyDaysAgo=Math.floor(dateThirtyDaysAgo.getTime()/1000);$("#campaign-teplates").hide()
$(document).ready(async function(){Webflow.push(function(){$('form').submit(function(){return false;});});queryString=window.location.search;urlParams=new URLSearchParams(queryString);if(urlParams.has('search')||urlParams.has('id')||urlParams.has('template')){text="Fetching your requested payload..."
if(urlParams.has('search')){text="Searching for your requested payloads..."}else if(urlParams.has('template')){text="Fetching your requested template..."}
Swal.fire({title:'Loading...',html:text,icon:'info',showConfirmButton:false,showCancelButton:false,showCloseButton:false,allowOutsideClick:true,timer:2000,timerProgressBar:true,});}
$.getScript('/js/jquery.sparkline.min.js',function(){});checkDisplayLoginButton();runCookieConsent();populateCampaignTemplates();registerHomeListeners();buildPayloadsTable();});async function populateCampaignTemplates(){getTemplates().then((templates)=>{templates.sort(function(a,b){var nameA=a.template_name.toUpperCase();var nameB=b.template_name.toUpperCase();if(nameA<nameB){return 1;}
if(nameA>nameB){return-1;}});campaign_templates=templates;templates.forEach(function(template,index){$("#template-container").clone().prependTo(".swiper-wrapper").attr('id',template['template_id'])
$("#template-heading").html(`${template["template_name"]}`)
$("#template-description").html(template["template_description"])
$("#template-view-payloads").hide();$("#template-image").attr("src",template["image_url"])});$("#template-container").remove();buildSwiper();campaign_templates.forEach(function(template,index){$(`#${template['template_id']}`).mouseenter(function(){if(selected_template!=$(this).attr('id')){$(this).css("background-color",hover_over);}})
$(`#${template['template_id']}`).mouseleave(function(){if(selected_template!=$(this).attr('id')){$(this).css("background-color","#f5f7fa");}})
$(`#${template['template_id']}`).click(function(){$('#search-payloads').val("");campaign_templates.forEach(function(template,index){$(`#${template['template_id']}`).css("background-color","#f5f7fa");});$(this).css("background-color",hover_over);selected_template=$(this).attr('id');updateTable($(this).attr('id'));})
$(`#${template['template_id']}`).css("cursor","pointer");});$("#campaign-templates").show()
$("#campaign-templates-loading").hide()}).catch((error)=>{console.log("Failed to retrieve campaign templates.")})}
async function updateTable(template_id){payloads_table.clearFilter();campaign_templates.forEach(function(template,index){$(`#${template['template_id']}`).css("background-color","#f5f7fa");if(template['template_id']==template_id){payloads_table.setFilter("recipe_id","in",template['recipe_ids']);$(`#${template['template_id']}`).css("background-color",hover_over);}});}
var sparklineFormatter=function(cell,formatterParams,onRendered){if(cell.getValue()==undefined){return;}
onRendered(function(){var values=Object.values(cell.getValue()['delivered']);if(values.length<2){return;}
$(cell.getElement()).sparkline(values,{width:"100%",height:"25px",type:"line",fillColor:"#80DCFF",lineColor:"#3FCBFF",spotColor:false,tooltipSuffix:"% delivered",maxSpotColor:false,minSpotColor:false,lineWidth:3,chartRangeMin:0,chartRangeMax:100,tooltipFormatter:function(sparkline,options,fields){return`<div style="width: 80px; height: 20px;margin: 0; padding: 0;font-weight: bold;">${fields.y}% delivered</div>`;}});});};async function buildPayloadsTable(){payloads_table=new Tabulator("#tabulator-payloads-table",{dataTree:true,dataTreeCollapseElement:"",dataTreeBranchElement:false,responsiveLayout:"true",layout:"fitColumns",index:"recipe_id",ajaxURL:`https://api.${window.location.host}/payloads`,ajaxConfig:{method:"GET",headers:{"Accept":"application/json","X-Requested-With":"XMLHttpRequest","Content-type":'application/json; charset=utf-8',"Access-Control-Allow-Origin":window.location.origin,},},ajaxResponse:function(url,params,response){for(let i=0;i<response.length;i++){if(response[i].added_epoch>epochTimeThirtyDaysAgo){var added_datestring_full=epochToHuman(response[i].added_epoch.toString());var added_datestring=added_datestring_full.substring(0,10);response[i].name=`${response[i].name}&nbsp;&nbsp;<div style="background-color:#A0E5FF;" class="tag" title="Added ${added_datestring}"><b>NEW!</b></div>`;}}
return response;},dataTreeExpandElement:"<img style='display:none'/>",dataTreeCollapseElement:"<img style='display:none'/>",selectableRows:1,selectableRowsCheck:function(row){return row.getData()["extension"]!="blank";},height:"750px",initialSort:[{column:"name",dir:"asc"},{column:"added_epoch",dir:"desc"}],columns:[{field:"extension",responsive:1,headerSort:false,headerHozAlign:"center",width:65,hozAlign:"center",formatter:function(cell,formatterParams,onRendered){var extension=cell.getValue()
if(extension=="blank"){return""}
return`<img src="/images/${extension}.png" alt="${extension}" loading='lazy' title="${extension}" width="15" height="15" onerror="this.src='/images/blank.png'">`}},{title:"Payload Name",field:"name",resizable:false,tooltip:false,responsive:0,minWidth:400,formatter:"html",},{title:"Global Deliverability",field:"metrics_history",headerSort:false,resizable:false,responsive:3,width:200,formatter:sparklineFormatter},{visible:false,field:"recipe_id",},{visible:false,field:"added_epoch",},{visible:false,field:"id",},{visible:false,field:"description",},{visible:false,field:"tags",},{visible:false,field:"image",},],});payloads_table.on("rowClick",async function(e,row){if(row.getTreeParent()){return;}
var action="collapse";payloads_table.getRows().forEach(function(row){if(row.getTreeChildren().length>0){findChildren(row,action)}});if(row.getTreeChildren().length>0){if(row.isTreeExpanded()){row.treeCollapse();return;}else{row.treeExpand();return;}}
if(!row.getTreeParent()&&row.getTreeChildren().length==0){old_data=row.getData();new_data={"id":old_data.id,"recipe_id":old_data.recipe_id,"name":"<div style='opacity:20%'>Loading...</div>","description":old_data.description+old_data.name+old_data.extension,"tags":old_data.tags,"extension":"blank","delivery":old_data.delivery,"image":old_data.image,};row.addTreeChild(new_data);row.treeExpand();retrieveRecipeInfo(row.getCell("recipe_id").getInitialValue());}});payloads_table.on("dataProcessed",function(data){$(`#${campaign_templates[campaign_templates.length - 1]['template_id']}`).css("background-color",hover_over);selected_template=campaign_templates[campaign_templates.length-1]['template_id'];if(urlParams.has('id')){global_recipe_id=urlParams.get('id');document.getElementById("search-payloads").value=global_recipe_id;var event=new Event('keyup');document.getElementById("search-payloads").dispatchEvent(event);safeClickRow();document.getElementById("campaign-templates").scrollIntoView();}else if(urlParams.has('search')){document.getElementById("search-payloads").value=urlParams.get('search');var event=new Event('keyup');document.getElementById("search-payloads").dispatchEvent(event);safeClickRow();document.getElementById("campaign-templates").scrollIntoView();}else if(urlParams.has('template')){var template_name_or_id=urlParams.get('template');for(var i=0;i<campaign_templates.length;i++){if(campaign_templates[i]['template_id']==template_name_or_id||campaign_templates[i]['template_name'].toLowerCase().replace(/ /g,"_").includes(template_name_or_id)){document.getElementById(campaign_templates[i]['template_id']).dispatchEvent(new Event('click'));for(var j=0;j<campaign_templates.length;j++){if($(`#${campaign_templates[i]['template_id']}`).hasClass("swiper-slide-active")){break;}else{$(".swiper-button-next")[0].click();}}
break;}}
safeClickRow();document.getElementById("campaign-templates").scrollIntoView();}else{safeClickRow();}});}
async function safeClickRow(){if(payloads_table.getData().length>0){try{$(".tabulator-cell")[0].click()}catch(error){}}}
function findChildren(row,action){if(action=="expand"){row.treeExpand();}else{row.treeCollapse()};var childRows=row.getTreeChildren();if(childRows.length>0){childRows.forEach(function(child){if(child.getTreeChildren().length>0){findChildren(child,action)}})}}
async function retrieveRecipeInfo(recipe_id){global_recipe_id=recipe_id;return new Promise(function(resolve,reject){getRecipeInfo(recipe_id).then(response=>{try{global_recipe_id=response['recipe_id'];}catch{}
displayPayloadInfo(response);resolve();}).catch(function(err){global_recipe_id="";payloads_table.clearFilter();resolve();});});}
function getVimeoImage(url){return new Promise((resolve,reject)=>{$.ajax({type:'GET',url:url,success:function(data){resolve(JSON.parse(data.substr(0,data.length-2).substr(15)));},error:function(request,error){resolve("");}});});}
function getVimeoLinks(data){return new Promise(async(resolve,reject)=>{for(let index=0;index<data.length;index++){item=data[index];if(item.includes("vimeo.com")){let video_id=item.split("/")[3];var url=`https://vimeo.com/api/v2/video/${video_id}.json?callback=showThumb`
await getVimeoImage(url).then((data)=>{resolve(data);return;});}}
reject("");});}
function displayPayloadInfo(payload_info){var row=payloads_table.searchRows("recipe_id","=",payload_info.recipe_id);references_string=""
if(row[0]){tags_string=""
if(payload_info['tags'].length!=0){payload_info['tags'].forEach(function(item,index){tags_string=tags_string+`<div style="background-color:  #A0E5FF;" class="tag">${item}</div> `;});}
if(payload_info['references'].length!=0){indent=false
payload_info['references'].forEach(function(item,index){if(item.includes("https://x.com/")||item.includes("https://twitter.com/")||item.includes("https://vimeo.com/")||item.includes("https://app.any.run/")){indent=true}});payload_info['references'].forEach(function(item,index){if(item.includes("https://x.com/")||item.includes("https://twitter.com/")){references_string=references_string+"<img src='/images/x.png' width='15' height='15' alt=''>&nbsp&nbsp";}else if(item.includes("https://vimeo.com/")){references_string=references_string+"<img src='/images/vimeo.png' width='15' height='15' alt=''>&nbsp&nbsp";}else if(item.includes("https://app.any.run/")){references_string=references_string+"<img src='/images/anyrun.png' width='15' height='15' alt=''>&nbsp&nbsp";}else if(indent){references_string=references_string+"<img src='/images/.png' width='15' height='15' alt=''>&nbsp&nbsp";}
references_string=references_string+`<a href="${item}">${item}</a><br>`;});}
getVimeoLinks(payload_info['references']).then((vimeo_links)=>{updatePayloadChild(row[0],payload_info.payload_id,payload_info.description,tags_string,references_string,payload_info.image,vimeo_links);}).catch((error)=>{updatePayloadChild(row[0],payload_info.payload_id,payload_info.description,tags_string,references_string,payload_info.image);});}}
async function updatePayloadChild(row,payload_id,description,tags_string,references_string,image,vimeo_links=""){var table_width=document.getElementById("tabulator-payloads-table").offsetWidth-60;vimeo_string=""
if(vimeo_links!=""){vimeo_string=vimeo_string+`<br><a href="${vimeo_links["url"]}" target="_blank"><img src=${vimeo_links["thumbnail_medium"]} width="200" height="150" alt=""></a><br>`}
new_data_object=`
    <div style="max-width:${table_width}px;text-wrap:pretty;white-space:initial">
        ${description}<br><br>
        ${tags_string}<br><br>
        ${references_string}
        ${vimeo_string}
        <br>
        

    </div>
    <img style="height:65px;cursor:pointer" src="data:image/png;base64,${image}" onclick="showLargePayloadImage('${image}')"><br><br>
    <img src="../images/download.png" width="20" height="20" alt=""><a href="#!" title="Download" onclick="downloadPayload('${payload_id}')">&nbsp&nbsp<u>Download</u></a>&nbsp&nbsp&nbsp&nbsp  
    <img src="../images/share.png" width="20" height="20" alt=""><a href="#!" title="Share" onclick="copyToClipboard('https://${window.location.hostname}?id=${row.getData().recipe_id}')">&nbsp&nbsp<u>Share</u></a>
    `
old_data=row.getData();new_data={"id":old_data.id,"recipe_id":old_data.recipe_id,"name":new_data_object,"description":old_data.description+old_data.name+old_data.extension,"tags":old_data.tags,"extension":"blank","delivery":old_data.delivery,"image":old_data.image,};row.getTreeChildren()[0].update(new_data);}
async function copyToClipboard(link){navigator.clipboard.writeText(link).then(function(){Swal.fire({title:'Copied to Clipboard',html:`A direct link to this payload has been copied to your clipboard.<br><br>Alternatively, use this link: <a href="${link}" target="_blank">${link}</a>.`,icon:'info',confirmButtonColor:'#3FCBFF'})}).catch(function(){Swal.fire({icon:'info',title:'Share this Link',html:`Use this link to go directly to this payload: <a href="${link}" target="_blank">${link}</a>.`,confirmButtonColor:'#3FCBFF'})});}
async function showLargePayloadImage(image){let img=document.createElement('img');img.src=`data:image/png;base64,${image}`;let realWidth=img.naturalWidth;let realHeight=img.naturalHeight;Swal.fire({showCancelButton:false,showConfirmButton:false,width:realWidth+100,html:`<img src="${img.src}" height="${realHeight}" width="${realWidth}" id="payload_image_large" alt="">`,})}
async function getTemplates(){return new Promise((resolve,reject)=>{url=`https://api.delivr.to/public/templates`
$.ajax({method:'GET',url:url,contentType:'application/json',statusCode:{200:function(responseObject,textStatus,jqXHR){resolve(responseObject)}},done:function done(){reject(null)},error:function ajaxError(){reject(null)}});})}
async function buildSwiper(){var mySwiper=new Swiper('.swiper-container',{direction:'horizontal',loop:true,slidesPerView:1,breakpoints:{768:{slidesPerView:3,loop:false,},480:{slidesPerView:1,loop:false,}},pagination:{el:'.swiper-pagination',},navigation:{nextEl:'.swiper-button-next',prevEl:'.swiper-button-prev',}})}
async function registerHomeListeners(){$("#lets-go-button").click(()=>{startHealthCheckLite();});$("#got-a-code").click(()=>{handleCode('Enter your code');});$('#search-payloads').on('keyup change',function(){var query=$('#search-payloads').val();if(query==''){payloads_table.clearFilter(true);}else{payloads_table.setFilter([[{field:"name",type:"like",value:query},{field:"tags",type:"like",value:query},{field:"description",type:"like",value:query},{field:"recipe_id",type:"like",value:query},]]);}});}
async function startHealthCheckLite(){if(!isValidEmailAddress($('#lets-go-email').val())){Swal.fire({title:'Invalid email address',text:'Please enter a valid email address.',icon:'error',confirmButtonText:'OK'})
return;}
Swal.fire({html:`Hit <i>Send Code</i> and we'll email you a code to verify that you own the address.<br><br>
        <p style="opacity:50%">Note: Allowlist the sending domain for best results. <a style="normal-link" href="https://docs.delivr.to/docs/gettingstarted/preparing_your_environment.html">Read more</a>.</p> 

        `,icon:'info',width:600,confirmButtonColor:'#3FCBFF',showCancelButton:true,confirmButtonText:"Send Code",denyButtonText:`Cancel`}).then((result)=>{if(result.isConfirmed){Swal.fire({didOpen:()=>{Swal.showLoading()},});issueSignUpCode().then(async response=>{handleCode('Code sent');}).catch((error)=>{if(error.responseJSON['error'].includes("Temporary email")){Swal.fire({title:'Temporary email address detected',text:'To prevent abuse, temporary email addresses are not permitted. Please try again using a personal or business address.',icon:'error',confirmButtonText:'OK',confirmButtonColor:'#3FCBFF'})}else{fireDefaultHealthCheckError();}});}})}
async function handleCode(title){const result=await Swal.fire({title:title,input:'number',inputPlaceholder:'Enter code',showCancelButton:true,confirmButtonText:'Submit',showLoaderOnConfirm:true,confirmButtonColor:'#3FCBFF',denyButtonText:`Cancel`,customClass:{validationMessage:'Validating...',},preConfirm:async(code)=>{if(!code){Swal.showValidationMessage('<i class="fa fa-info-circle"></i> Please enter a code or click cancel.')}else{try{return await verifySignUpCode(code)}catch(error){if(error.responseJSON['error'].includes("expired")){resendSignUpCode();Swal.showValidationMessage('<i class="fa fa-info-circle"></i> A new code has been issued as the old one had expired. Please try again.')}else if(error.responseJSON['error'].includes("not match")){Swal.showValidationMessage('<i class="fa fa-info-circle"></i> Your code is incorrect. Please try again.')}else{Swal.showValidationMessage('<i class="fa fa-info-circle"></i> An unknown error has occurred. Please try again.')}}}}})
if(result.isConfirmed){var token=result['value']['token']
Swal.fire({title:'Success!',html:`Email verified - you can now start your health check! ðŸš€`,icon:'success',confirmButtonText:'Start',width:600,confirmButtonColor:'#3FCBFF',}).then((result)=>{if(result.isConfirmed){Swal.fire({didOpen:()=>{Swal.showLoading()},});scheduleMiniHealthCheck(token,$('#lets-go-email').val()).then((result)=>{console.log(result)
Swal.fire({title:'Success!',html:`Your health check has started - check your inbox for the results! ðŸ“¬`,icon:'success',confirmButtonText:'OK',width:600,confirmButtonColor:'#3FCBFF',})}).catch((error)=>{fireDefaultHealthCheckError();});}})};}
async function resendSignUpCode(){return new Promise((resolve,reject)=>{$.ajax({method:'POST',url:'https://api.delivr.to/public/resend',contentType:'application/json',data:JSON.stringify({"email":$('#lets-go-email').val()}),statusCode:{204:function(responseObject,textStatus,jqXHR){resolve(true)}},done:function done(){reject(null)},error:function ajaxError(jqXHR,textStatus,errorThrown){reject(jqXHR)}});})}
async function fireDefaultHealthCheckError(){Swal.fire({title:'Failed to launch health check',html:`An unknown error has occurred.<br><br>
        If you already have an account, please sign in and launch the health check from your dashboard. If you've forgotten your password, or are resuming a previous healthcheck, you can reset your password using the <a href="https://auth.${window.location.hostname}/forgotPassword?client_id=1vrddd8j39trhppuot7be6om5c&response_type=code&scope=aws.cognito.signin.user.admin+email+openid+profile&redirect_uri=https%3A%2F%2F${window.location.hostname}%2Fauth%2Fcallback&state=%2Fapp%2Fdashboard">Forgot Password</a> option.`,icon:'error',confirmButtonText:'OK',confirmButtonColor:'#3FCBFF'})}
async function scheduleMiniHealthCheck(token,email){return new Promise((resolve,reject)=>{target_template_id=""
try{$.ajax({method:'GET',url:'https://api.delivr.to/templates',headers:{Authorization:token,},contentType:'application/json',success:async function success(templates){target_template_id=''
for(var i=0;i<templates.length;i++){if(templates[i]["template_name"]=="delivr.to's Top 10 Payloads"){target_template_id=templates[i]["template_id"]
break;}}
if(target_template_id==''){reject(null)}else{var data=new Object();data.template_id=target_template_id;data.campaign_name=`Mini Health Check`;data.recipient=email;data.email_results=true
data.include_disabled_integrations=false
data.sender="default"
data.as_links=true;data.as_attachments=true;$.ajax({method:'POST',url:'https://api.delivr.to/campaign',headers:{Authorization:token,},data:JSON.stringify(data),contentType:'application/json',statusCode:{200:function(responseObject,textStatus,jqXHR){resolve(true)}},done:function done(){reject(null)},error:function ajaxError(){reject(null)}});}},error:function ajaxError(jqXHR,textStatus,errorThrown){reject(null)}});}catch(error){reject(null)}})}
async function verifySignUpCode(code){return new Promise((resolve,reject)=>{$.ajax({method:'POST',url:'https://api.delivr.to/public/verify',contentType:'application/json',data:JSON.stringify({"email":$('#lets-go-email').val(),"code":code}),statusCode:{200:function(responseObject,textStatus,jqXHR){resolve(responseObject)}},done:function done(){reject(null)},error:function ajaxError(jqXHR,textStatus,errorThrown){reject(jqXHR)}});})}
async function issueSignUpCode(){return new Promise((resolve,reject)=>{$.ajax({method:'POST',url:'https://api.delivr.to/public/signup',contentType:'application/json',data:JSON.stringify({"email":$('#lets-go-email').val()}),statusCode:{204:function(responseObject,textStatus,jqXHR){resolve(true)}},done:function done(){reject(null)},error:function ajaxError(jqXHR,textStatus,errorThrown){reject(jqXHR)}});})}
